name: Extract Text from PDF

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdfplumber requests

      - name: Run text extraction script
        run: python extract_text.py

      - name: Debug
        run: |
          ls -la

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');

            // Set Git user info
            execSync('git config --global user.name "github-actions[bot]"');
            execSync('git config --global user.email "github-actions[bot]@users.noreply.github.com"');

            // Add and commit changes
            execSync('git add output.txt');
            execSync('git commit -m "Update extracted text"');

            // Push changes
            execSync('git push origin HEAD:main');
