name: Extract Text from PDF

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdfplumber requests

      - name: Run text extraction script
        run: python extract_text.py

      - name: Debug
        run: |
          ls -la

      - name: Commit changes
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.txt
          git commit -m "Update extracted text"
          git remote set-url origin https://x-access-token:$ACCESS_TOKEN@github.com/${{ github.repository }}.git
          git push origin HEAD:main
